MP - Added Capacity per User Feature
ucsb-cs156-m23/proj-happycows-m23-10am-4 pull request #35
Opened 2023-08-12 22:42 UTC by MPriston

## Overview

In this PR we add the ability to describe a capacity per-user when creating a new common or editing it. This change introduces a new field on the create and edit commons form that gives the admin the ability to specify a per-user capacity for each commons.

It utilizes the following formula to calculate the effective capacity of the common when doing health calculations
`max(capacityPerUser * joinedUsers.size(), carryingCapacity)`

## Screenshots (Optional)

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function.

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #3

2023-08-12 22:44 UTC, MPriston commented
Currently working on the Frontend of the changes

2023-08-12 23:56 UTC, MPriston commented
Currently working on some bugs

2023-08-13 04:01 UTC, MPriston commented
Working on test coverage for new variables

2023-08-13 04:31 UTC, MPriston commented
Test Coverage is good, need to update, jobs notifications to display correct information

2023-08-15 20:23 UTC, publicqi commented on src/main/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategies.java
Not your code, but why do we add health if the capacity is reached?

2023-08-15 21:48 UTC, publicqi commented on src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
Is this (`numUsers`) passed in by frontend? If so, we should not trust that.

2023-08-15 21:52 UTC, publicqi approved these changes

2023-08-15 21:52 UTC, dscpsyl approved these changes, later dismissed
LGTM! Had a team code review in person over this PR.

2023-08-15 21:52 UTC, publicqi submitted a review, later dismissed

2023-08-21 21:19 UTC, pconrad requested changes
It appears that the fixtures may send future developers mixed signals about the rules governing effectiveCapacity.

Also: it appears that this PR puts everything in place for effectiveCapacity *except* the part where you actually start to use it to govern the health updates.  You probably should do that part FIRST before exposing the value in the user interface.

I am a fan of smaller PRs, but in this case, the way the PRs are structured puts a feature in the hands of end users in a way that would be misleading.   

The backend should be updated to *use* effective capacity before the PR goes in that exposes it to end users.

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 42,
If the commons has 50 players, and the capacity per user is 13, then 13*50=650.   Shouldn't the effective capacity be 650 in that scenario?

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 123,
If the totalPlayers are 50 and the capacityPerUser is 11, shouldn't the effectiveCapacity be 550?

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 100,
If the totalPlayers are 50, and the capacityPerUser is 10, shouldn't the effectiveCapacity be 500?

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 100,
Please check this effectiveCapacity.

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 100,
Please check this effectiveCapacity.

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 100,
Please check this effectiveCapacity.

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 100,
Please check this effectiveCapacity.

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 100,
Please check this effectiveCapacity.

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 100,
Please check this effectiveCapacity.

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsFixtures.js
> +            "effectiveCapacity": 100,
Please check this effectiveCapacity.

2023-08-21 21:19 UTC, pconrad commented on frontend/src/fixtures/commonsPlusFixtures.js
> +                "effectiveCapacity": 100,
Please check all of the effectiveCapacities to make sure they are internally consistent.

2023-08-21 21:31 UTC, pconrad requested changes
Check out this segment of code in `src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java`

Should this be updated?

```java
 int carryingCapacity = commons.getCarryingCapacity();
            Iterable<UserCommons> allUserCommons = userCommonsRepository.findByCommonsId(commons.getId());
            Integer totalCows = commonsRepository.getNumCows(commons.getId()).orElseThrow(() -> new RuntimeException("Error calling getNumCows(" + commons.getId() + ")"));
            var isAboveCapacity = totalCows > carryingCapacity;
```

2023-08-21 22:36 UTC, pconrad approved these changes
Nice job!

2023-08-21 22:37 UTC, merged