Home page now shows different backgrounds depending on time of day
ucsb-cs156-m23/proj-happycows-m23-10am-4 pull request #58
Opened 2023-08-16 07:15 UTC by dscpsyl

## Overview
In this PR, the homepage will show a different background depending on the time of day in local time. This helps with user experience and improves the overall novelness of the game. A nice-to-have feature. All images are from [Unsplash](https://unsplash.com/) and are thus free for use. 

## Screenshots (Optional)
<img width="1528" alt="Screenshot 2023-08-15 at 11 44 59 PM" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/assets/41165204/053353f5-fc67-4652-8c68-4bc4630cc6c5">

## Storybook links

* https://ucsb-cs156-m23.github.io/proj-happycows-m23-10am-4/prs/58/storybook/?path=/story/pages-homepage--morning
* https://ucsb-cs156-m23.github.io/proj-happycows-m23-10am-4/prs/58/storybook/?path=/story/pages-homepage--day
* https://ucsb-cs156-m23.github.io/proj-happycows-m23-10am-4/prs/58/storybook/?path=/story/pages-homepage--evening
* https://ucsb-cs156-m23.github.io/proj-happycows-m23-10am-4/prs/58/storybook/?path=/story/pages-homepage--night

## Feedback Request (Optional)
If you have any ideas of what better images to use, please feel free to share. Please also reference the current issue for the timing of background changes and let me know if you disagree with them. 

## Tests
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #20

2023-08-16 22:13 UTC, iain801 commented
Looks like many mutants are surviving in the .js files.

2023-08-16 23:12 UTC, dscpsyl commented
@iain801 Should be fix now

2023-08-17 21:50 UTC, iain801 submitted a review, later dismissed
Looks good to me, works on dokku-qa!

2023-08-17 21:51 UTC, yuanchenmeng submitted a review, later dismissed
LGTM!

2023-08-21 22:25 UTC, pconrad requested changes
I've suggested a couple of changes that will allow you to show off this feature in the storybook.  That's helpful, because otherwise, there's very little way to show it off.

See the changes that I suggested in the HomePage.js component first. Then, we can add something like this in:



```js

const Template = (args) => <HomePage  {...args} />;

export const Morning = Template.bind({});
Morning.args = {
    hour: 8
};

export const Day = Template.bind({});
Day.args = {
    hour: 10
};

// etc for Evening and Night

```

2023-08-21 22:25 UTC, pconrad commented on frontend/src/main/pages/HomePage.js
>  export default function HomePage() {
```suggestion
export default function HomePage({hour=null}) {
```

This suggestion goes along with the one below.

2023-08-21 22:25 UTC, pconrad commented on frontend/src/main/pages/HomePage.js
> +  const time = new Date().getHours();
This suggestion goes along with the one above, to have a parameter hour that, by default, is null, but can be overridden (this is for use with storybook).   Unless I'm mistaken, these two suggestions won't change any existing functionality but will allow you to add some stories to show what the home page will look like at different times of day.

```suggestion
  const time = ( hour===null)  ? new Date().getHours() : hour;
```

2023-08-21 23:44 UTC, dscpsyl commented
@pconrad Thank you for the suggestions! Storybook changes have been implemented and are now working.

2023-08-22 07:27 UTC, iain801 approved these changes
I'm assuming the @phtcon's fixes work, lgtm!

2023-08-22 18:38 UTC, pconrad approved these changes
LGTM

2023-08-22 18:38 UTC, merged