FEATURE: Added new interface for Update health and Milk Cows Jobs
ucsb-cs156-m23/proj-happycows-m23-10am-4 pull request #82
Opened 2023-08-20 20:15 UTC by MPriston

## Overview

In this PR, we implement the new frontend interfaces for Updating the cows' health and milking commons. This gives the user the ability to choose a single common or all of them when running the jobs

## DEPENDENCIES
In order for this PR to be merged and work properly, PR #81 needs to be closed first 

## Screenshots (Optional)

![image](https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/assets/20800629/5346beed-389f-4672-bdf6-8285d5c4735e)
![image](https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/assets/20800629/eccc4f91-2f36-46c6-852a-d51a6adb3659)

## Validation (Optional)

1. See <> for newly implemented components

## Tests

- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
Closes #11
Closes #45

2023-08-20 23:25 UTC, iain801 submitted a review, later dismissed
Nice looking UI! Assume functions have been tested

2023-08-21 03:58 UTC, chriscerie requested changes

2023-08-21 03:58 UTC, chriscerie commented on frontend/src/main/components/Jobs/MilkCowsJobForm.js
>    }
Avoid setting state in render unless under *very* special circumstances. Set initial values in useState or fallback to default values.

2023-08-21 03:58 UTC, chriscerie commented on frontend/src/main/components/Jobs/UpdateCowHealthForm.js
> +  }
Same thing here.

2023-08-23 22:43 UTC, closed without merging