Remove test job from front end
ucsb-cs156-m23/proj-happycows-m23-10am-4 pull request #90
Opened 2023-08-22 22:07 UTC by dscpsyl

## Overview

In this PR, the test job function is removed from the user-facing front end. It is still available in the Swagger backend. 

## Screenshots (Optional)
<img width="1328" alt="Screenshot 2023-08-22 at 3 04 52 PM" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/assets/41165204/c1d0426c-8d66-40e9-8e34-f3802ebfa8fe">

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function.

## Tests

- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #25

2023-08-23 06:16 UTC, publicqi reviewed
Should we just delete the code to avoid confusion for future developers or commenting out the code?

Other than that, the code looks good to me.

2023-08-23 22:07 UTC, chriscerie commented
> Should we just delete the code to avoid confusion for future developers or commenting out the code?

Yes. There’s very few cases where commented code is beneficial to readers, and this is not one of them.

2023-08-24 18:25 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
> +// import TestJobForm from "main/components/Jobs/TestJobForm";
Ack!  What have we said about commenting out code in production?

It's fine to comment out while testing, but when you make a PR, the commented out code should go bye-bye.

2023-08-24 18:25 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
> +  // const objectToAxiosParamsTestJob = (data) => ({
here too

2023-08-24 18:25 UTC, pconrad commented on frontend/src/main/pages/AdminJobsPage.js
> +  // {
and here

2023-08-24 18:25 UTC, pconrad requested changes
shaking my head... we've talked about commented out code, have we not?

2023-08-24 19:17 UTC, dscpsyl commented
That is my bad. This PR is not ready yet. I'll close this PR and recreate one. There's still more testing to be done and I'm still experimenting

2023-08-24 19:17 UTC, closed without merging